production:
  clear_solid_queue_finished_jobs:
    command: "SolidQueue::Job.clear_finished_in_batches(sleep_between_batches: 0.3)"
    schedule: every week

  matches_pl:
    class: MatchesJob
    args: ['PL', 2026]
    schedule: every day

  competitions_pl:
    class: CompetitionsJob
    args: ['PL']
    schedule: every day
  
#  rankings_pl:
#    class: SeasonRankingsJob
#    args: ['PL', 2026]
#    schedule: every day

  matches_wc:
    class: MatchesJob
    args: ['WC', 2026]
    schedule: every 1 minutes

  competitions_wc:
    class: CompetitionsJob
    args: ['WC']
    schedule: every 1 minutes

  rankings_wc:
    class: SeasonRankingsJob
    args: ['WC', 2026]
    schedule: every 1 minutes

  reminder_emails:
    class: ReminderJob
    schedule: every day at 7
